export const LABELS = {
  BLOCKS_TABLE: 'BLOCK_TABLE',
  PAYMENT_TABLE: 'PAYMENT_TABLE',
  PARTIALS_TABLE: 'PARTIALS_TABLE',
  WIN_BLOCKS_TABLE: 'WIN_BLOCKS_TABLE',
  RANK_TABLE: 'RANK_TABLE',
  DESC: 'DESC',
  ASCE: 'ASCE',
}